/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as ApiResearchProjectRouteImport } from './routes/api/research-project'
import { Route as ApiGenerateStrategiesRouteImport } from './routes/api/generate-strategies'
import { Route as ApiGenerateImagesRouteImport } from './routes/api/generate-images'
import { Route as ApiGenerateElementsRouteImport } from './routes/api/generate-elements'
import { Route as ApiDebugLlmRouteImport } from './routes/api/debug-llm'
import { Route as ApiClassifyProjectRouteImport } from './routes/api/classify-project'
import { Route as ApiAnalyzeProductImagesRouteImport } from './routes/api/analyze-product-images'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppProductNewRouteImport } from './routes/app.product.new'
import { Route as AppBrandNewRouteImport } from './routes/app.brand.new'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AppProjectProjectIdIndexRouteImport } from './routes/app.project.$projectId.index'
import { Route as AppProjectProjectIdGeneratingRouteImport } from './routes/app.project.$projectId.generating'
import { Route as AppProjectProjectIdConceptConceptIdRouteImport } from './routes/app.project.$projectId.concept.$conceptId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const ApiResearchProjectRoute = ApiResearchProjectRouteImport.update({
  id: '/api/research-project',
  path: '/api/research-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateStrategiesRoute = ApiGenerateStrategiesRouteImport.update({
  id: '/api/generate-strategies',
  path: '/api/generate-strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImagesRoute = ApiGenerateImagesRouteImport.update({
  id: '/api/generate-images',
  path: '/api/generate-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateElementsRoute = ApiGenerateElementsRouteImport.update({
  id: '/api/generate-elements',
  path: '/api/generate-elements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugLlmRoute = ApiDebugLlmRouteImport.update({
  id: '/api/debug-llm',
  path: '/api/debug-llm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassifyProjectRoute = ApiClassifyProjectRouteImport.update({
  id: '/api/classify-project',
  path: '/api/classify-project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeProductImagesRoute = ApiAnalyzeProductImagesRouteImport.update({
  id: '/api/analyze-product-images',
  path: '/api/analyze-product-images',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProductNewRoute = AppProductNewRouteImport.update({
  id: '/product/new',
  path: '/product/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandNewRoute = AppBrandNewRouteImport.update({
  id: '/brand/new',
  path: '/brand/new',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProjectProjectIdIndexRoute =
  AppProjectProjectIdIndexRouteImport.update({
    id: '/project/$projectId/',
    path: '/project/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectProjectIdGeneratingRoute =
  AppProjectProjectIdGeneratingRouteImport.update({
    id: '/project/$projectId/generating',
    path: '/project/$projectId/generating',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectProjectIdConceptConceptIdRoute =
  AppProjectProjectIdConceptConceptIdRouteImport.update({
    id: '/project/$projectId/concept/$conceptId',
    path: '/project/$projectId/concept/$conceptId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/analyze-product-images': typeof ApiAnalyzeProductImagesRoute
  '/api/classify-project': typeof ApiClassifyProjectRoute
  '/api/debug-llm': typeof ApiDebugLlmRoute
  '/api/generate-elements': typeof ApiGenerateElementsRoute
  '/api/generate-images': typeof ApiGenerateImagesRoute
  '/api/generate-strategies': typeof ApiGenerateStrategiesRoute
  '/api/research-project': typeof ApiResearchProjectRoute
  '/app/account': typeof AppAccountRoute
  '/app/new': typeof AppNewRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/brand/new': typeof AppBrandNewRoute
  '/app/product/new': typeof AppProductNewRoute
  '/app/project/$projectId/generating': typeof AppProjectProjectIdGeneratingRoute
  '/app/project/$projectId/': typeof AppProjectProjectIdIndexRoute
  '/app/project/$projectId/concept/$conceptId': typeof AppProjectProjectIdConceptConceptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/analyze-product-images': typeof ApiAnalyzeProductImagesRoute
  '/api/classify-project': typeof ApiClassifyProjectRoute
  '/api/debug-llm': typeof ApiDebugLlmRoute
  '/api/generate-elements': typeof ApiGenerateElementsRoute
  '/api/generate-images': typeof ApiGenerateImagesRoute
  '/api/generate-strategies': typeof ApiGenerateStrategiesRoute
  '/api/research-project': typeof ApiResearchProjectRoute
  '/app/account': typeof AppAccountRoute
  '/app/new': typeof AppNewRoute
  '/app/projects': typeof AppProjectsRoute
  '/app': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/brand/new': typeof AppBrandNewRoute
  '/app/product/new': typeof AppProductNewRoute
  '/app/project/$projectId/generating': typeof AppProjectProjectIdGeneratingRoute
  '/app/project/$projectId': typeof AppProjectProjectIdIndexRoute
  '/app/project/$projectId/concept/$conceptId': typeof AppProjectProjectIdConceptConceptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/analyze-product-images': typeof ApiAnalyzeProductImagesRoute
  '/api/classify-project': typeof ApiClassifyProjectRoute
  '/api/debug-llm': typeof ApiDebugLlmRoute
  '/api/generate-elements': typeof ApiGenerateElementsRoute
  '/api/generate-images': typeof ApiGenerateImagesRoute
  '/api/generate-strategies': typeof ApiGenerateStrategiesRoute
  '/api/research-project': typeof ApiResearchProjectRoute
  '/app/account': typeof AppAccountRoute
  '/app/new': typeof AppNewRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/brand/new': typeof AppBrandNewRoute
  '/app/product/new': typeof AppProductNewRoute
  '/app/project/$projectId/generating': typeof AppProjectProjectIdGeneratingRoute
  '/app/project/$projectId/': typeof AppProjectProjectIdIndexRoute
  '/app/project/$projectId/concept/$conceptId': typeof AppProjectProjectIdConceptConceptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/analyze-product-images'
    | '/api/classify-project'
    | '/api/debug-llm'
    | '/api/generate-elements'
    | '/api/generate-images'
    | '/api/generate-strategies'
    | '/api/research-project'
    | '/app/account'
    | '/app/new'
    | '/app/projects'
    | '/app/'
    | '/.mcp/invoke-tool/$tool'
    | '/app/brand/new'
    | '/app/product/new'
    | '/app/project/$projectId/generating'
    | '/app/project/$projectId/'
    | '/app/project/$projectId/concept/$conceptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/analyze-product-images'
    | '/api/classify-project'
    | '/api/debug-llm'
    | '/api/generate-elements'
    | '/api/generate-images'
    | '/api/generate-strategies'
    | '/api/research-project'
    | '/app/account'
    | '/app/new'
    | '/app/projects'
    | '/app'
    | '/.mcp/invoke-tool/$tool'
    | '/app/brand/new'
    | '/app/product/new'
    | '/app/project/$projectId/generating'
    | '/app/project/$projectId'
    | '/app/project/$projectId/concept/$conceptId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/analyze-product-images'
    | '/api/classify-project'
    | '/api/debug-llm'
    | '/api/generate-elements'
    | '/api/generate-images'
    | '/api/generate-strategies'
    | '/api/research-project'
    | '/app/account'
    | '/app/new'
    | '/app/projects'
    | '/app/'
    | '/.mcp/invoke-tool/$tool'
    | '/app/brand/new'
    | '/app/product/new'
    | '/app/project/$projectId/generating'
    | '/app/project/$projectId/'
    | '/app/project/$projectId/concept/$conceptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAnalyzeProductImagesRoute: typeof ApiAnalyzeProductImagesRoute
  ApiClassifyProjectRoute: typeof ApiClassifyProjectRoute
  ApiDebugLlmRoute: typeof ApiDebugLlmRoute
  ApiGenerateElementsRoute: typeof ApiGenerateElementsRoute
  ApiGenerateImagesRoute: typeof ApiGenerateImagesRoute
  ApiGenerateStrategiesRoute: typeof ApiGenerateStrategiesRoute
  ApiResearchProjectRoute: typeof ApiResearchProjectRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/research-project': {
      id: '/api/research-project'
      path: '/api/research-project'
      fullPath: '/api/research-project'
      preLoaderRoute: typeof ApiResearchProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-strategies': {
      id: '/api/generate-strategies'
      path: '/api/generate-strategies'
      fullPath: '/api/generate-strategies'
      preLoaderRoute: typeof ApiGenerateStrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-images': {
      id: '/api/generate-images'
      path: '/api/generate-images'
      fullPath: '/api/generate-images'
      preLoaderRoute: typeof ApiGenerateImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-elements': {
      id: '/api/generate-elements'
      path: '/api/generate-elements'
      fullPath: '/api/generate-elements'
      preLoaderRoute: typeof ApiGenerateElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-llm': {
      id: '/api/debug-llm'
      path: '/api/debug-llm'
      fullPath: '/api/debug-llm'
      preLoaderRoute: typeof ApiDebugLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classify-project': {
      id: '/api/classify-project'
      path: '/api/classify-project'
      fullPath: '/api/classify-project'
      preLoaderRoute: typeof ApiClassifyProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-product-images': {
      id: '/api/analyze-product-images'
      path: '/api/analyze-product-images'
      fullPath: '/api/analyze-product-images'
      preLoaderRoute: typeof ApiAnalyzeProductImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/product/new': {
      id: '/app/product/new'
      path: '/product/new'
      fullPath: '/app/product/new'
      preLoaderRoute: typeof AppProductNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/brand/new': {
      id: '/app/brand/new'
      path: '/brand/new'
      fullPath: '/app/brand/new'
      preLoaderRoute: typeof AppBrandNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/project/$projectId/': {
      id: '/app/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/app/project/$projectId/'
      preLoaderRoute: typeof AppProjectProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/project/$projectId/generating': {
      id: '/app/project/$projectId/generating'
      path: '/project/$projectId/generating'
      fullPath: '/app/project/$projectId/generating'
      preLoaderRoute: typeof AppProjectProjectIdGeneratingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/project/$projectId/concept/$conceptId': {
      id: '/app/project/$projectId/concept/$conceptId'
      path: '/project/$projectId/concept/$conceptId'
      fullPath: '/app/project/$projectId/concept/$conceptId'
      preLoaderRoute: typeof AppProjectProjectIdConceptConceptIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppNewRoute: typeof AppNewRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBrandNewRoute: typeof AppBrandNewRoute
  AppProductNewRoute: typeof AppProductNewRoute
  AppProjectProjectIdGeneratingRoute: typeof AppProjectProjectIdGeneratingRoute
  AppProjectProjectIdIndexRoute: typeof AppProjectProjectIdIndexRoute
  AppProjectProjectIdConceptConceptIdRoute: typeof AppProjectProjectIdConceptConceptIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppNewRoute: AppNewRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBrandNewRoute: AppBrandNewRoute,
  AppProductNewRoute: AppProductNewRoute,
  AppProjectProjectIdGeneratingRoute: AppProjectProjectIdGeneratingRoute,
  AppProjectProjectIdIndexRoute: AppProjectProjectIdIndexRoute,
  AppProjectProjectIdConceptConceptIdRoute:
    AppProjectProjectIdConceptConceptIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAnalyzeProductImagesRoute: ApiAnalyzeProductImagesRoute,
  ApiClassifyProjectRoute: ApiClassifyProjectRoute,
  ApiDebugLlmRoute: ApiDebugLlmRoute,
  ApiGenerateElementsRoute: ApiGenerateElementsRoute,
  ApiGenerateImagesRoute: ApiGenerateImagesRoute,
  ApiGenerateStrategiesRoute: ApiGenerateStrategiesRoute,
  ApiResearchProjectRoute: ApiResearchProjectRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
